### ISSUE TITLE
cluster-rules in OpenMusic

### ISSUE THREAD

**Issue by enh3** [tanders/cluster-rules#1]
Hi Torsten,

Posting this here because I haven't been able to find your email address. I've been voraciously reading your various articles on constraint programming, and I find Cluster Engine really compelling. I know that Paulo Raposo has ported it to OpenMusic, but I'd love to have your vast cluster-rules extensions in OpenMusic as well. Do you think either this Common Lisp version or your PWGL version would be adaptable to OpenMusic? Thanks in advance and thank you for all your wonderful contributions!

Kjel

PS, I'm a pipe-organist and I couldn't help noticing you have some pipe-organ compositions on your website. Delightful stuff!

**Comment by tanders** [comment]
Dear Kjel,

Thanks for your interest. 

> I'd love to have your vast cluster-rules extensions in OpenMusic as well. Do you think either this Common Lisp version or your PWGL version would be adaptable to OpenMusic? 

What version of OpenMusic are we talking about here? Cluster Engine was originally defined for LispWorks (as part of PWGL), and later ported to the SBCL compiler. The SBCL port is pure Common Lisp, without any PWGL dependencies.

Is OpenMusic nowadays using one of these compilers? Then porting cluster-rules might not be a big deal. Otherwise, it would still be worth just giving it a try. Even if you see some some errors or at least warnings, most/all of the rule definitions might still work. Cluster Rules does not really use any low-level code, the SBCL version should be pretty portable if Cluster Engine itself already works on your target platform.

Is the user interface (UI) integration of OpenMusic requiring some extra code (e.g., code for defining the relevant boxes, their parameter default values etc.)? In the past, PWGL and earlier OpenMusic versions used a somewhat different UI definition format, so that might need some adaptation. It might be, that pure Common Lisp definitions can already be used in OpenMusic without any UI wrapper, but then some niceties like default values for relevant boxes might be missing. 

Beyond all this, there is also the Max library MOZ’Lib (https://github.com/JulienVincenot/MOZLib) which integrates Cluster Engine into a real-time context. AFAIK, Cluster Rules is already part of it too. However, I never used this environment. 

Anyway, good luck. Let me know how things go for you.

> I find Cluster Engine really compelling

Just for completeness, I did not define Cluster Engine itself, it was originally the work of Örjan Sanders, with later some minor contributions by others. 

> I haven't been able to find your email address

Feel free to reach out by email: torstenanders at [gmx.de](http://gmx.de/).

> I couldn't help noticing you have some pipe-organ compositions on your website

There has been a time long ago when I wanted to become a church musician. Organ music is still rather close to my heart. 

Best,
Torsten

**Comment by enh3** [comment]
Hi Torsten,

Thank you for your generous reply. I'm primarily referring to OM7 and/or OM-sharp (an OpenMusic derived project with some nice additions that's being developed in parallel with original OM). Unfortunately, both these projects are still compiled with LispWorks, and use their own flavour of method definitions called defmethod! for the UI, as you mentioned. As such your plain Common Lisp version of cluster-engine won't work in OM natively, but Paulo Raposo has done his own port ([Cluster-Engine-Library-for-OpenMusic](https://github.com/PHRaposo/Cluster-Engine-Library-for-OpenMusic)).

Actually, we've been discussing porting your cluster rules to OM over [here](https://discussion.forum.ircam.fr/t/cluster-rules-and-ta-utilities-libraries-dont-appear/65938/26) for reference. You're completely right that a significant amount of your Common Lisp version of cluster rules works out of the box, but without the UI niceties. I've created my own [repository](https://github.com/enh3/om-cluster-rules) which for the moment is mostly your code structured as an OpenMusic library. I'll be studying your library and trying to improve the port in the coming months where I have the time.

As for the pipe organ, if you ever find yourself in Montréal, you're more than welcome to come by l'église Saint-Édouard where I play the organ and I'd love to give you a tour. The organ doesn't have MIDI as it's a 1912 instrument that hasn't yet been brought into the digital age, but we do have a MIDI operated carillon.

Take care,
Kjel
